### PR TITLE
Fix + tests

### LINKED ISSUE #134: Group health doesnt allow to mark validators that are using signers as healthy

### PR DESCRIPTION
**Pull request by pahor167**
### Description

Validators that were using signer were not allowed to be marked as healthy. 

### Other changes

No other changes

### Tested

Automatic tests

### Related issues

- Fixes #134

### CODE REVIEW

File: lib/multiSig-tasks/execute-proposal.ts [hunk 1]
```diff
@@ -20,6 +20,8 @@ import {
 import { taskLogger } from "../logger";
 import { MULTISIG_EXECUTE_PROPOSAL } from "../tasksNames";
 
+export const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms))
```
Comment (soloseng) [inline lib/multiSig-tasks/execute-proposal.ts:23]: `delay` seems to be unused.

**Review by soloseng — APPROVED** [review]
LGTM 🚀

**Review by montera82 — APPROVED** [review]
:shipit:
